name: marketplace_app
description: Application mobile marketplace contrÃ´lÃ©e pour Ã©lectromÃ©nager, meubles, literie et dÃ©coration.

publish_to: 'none'

version: 1.0.0+1
# RELEASE NOTE: Bump versionCode (+1) for every Play Store / App Store upload.
# Example next release: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # HTTP & API
  http: ^1.1.0
  signalr_netcore: ^1.1.4
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # Image Handling
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  
  # UI Components
  
  # Phone Calls
  url_launcher: ^6.2.1
  
  # Form Validation
  intl: ^0.20.2
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  crypto: ^3.0.7
  http_parser: ^4.1.2
  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0
  google_sign_in: ^7.2.0
  app_links: ^6.1.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/fesh_bay_logo.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/config/app_config.json
    - assets/images/fesh_bay_logo.png 