workflows:
  ios-workflow:
    name: iOS Workflow

    instance_type: mac_mini_m2
    max_build_duration: 60

    working_directory: mobile/marketplace_app

    integrations:
      app_store_connect: Codemagic Flutter Build 2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files \
            com.youcef.cashbuy \
            --type IOS_APP_STORE \
            --create

      - name: Initialize keychain
        script: |
          keychain initialize

      - name: Apply provisioning profiles
        script: |
          xcode-project use-profiles --verbose

      - name: Get packages
        script: flutter pub get

      - name: Build IPA
        script: |
          flutter build ipa --release

    artifacts:
      - mobile/marketplace_app/build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true